config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  # ArticleEngagement entries are created on page load, so we would always be updating them
  put "articles/engagement", to: "article_engagements#update", as: :article_engagements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < OpenStruct
  # Return the engagement record for the article, or create one, with the current likes as a default value.
  #
  # NOTE: This isn't the most efficiant way of returning the likes for an article, as it will have a number of
  # issues such as n+1 queries, and needs to create a record for each article it finds on the first page load.
  # However, for the purposes of this test, it is a nice way of encapsulating the functionality. With more records,
  # or in a production system, the data would be best stored in Redis, or a single record that can be retreived with
  # a one query.
  def engagement
    @engagement ||= ArticleEngagement.find_or_create_by(article_id: id) { |ae| ae.likes = reactions["likes"] }
  end

  # Parse the created_at date for an article and return the format required
  #
  # @return [String]
  def date_added
    return "Unknown" if created_at.blank?

    created_at.to_time.strftime("%a %b %e %Y")
  end

  # Return the image SRC for an article
  #
  # @return [String]
  def image
    return "" if images.blank?

    images.first.dig("files", "medium")
  end

  # Allow us to use rails render methods without specifying the full path
  #
  # @return [String]
  def to_partial_path
    "articles/article"
  end
end

app/models/article_engagement.rb
# frozen_string_literal: true

class ArticleEngagement < ApplicationRecord
  validates_presence_of :article_id

  # Increment our likes for this engagement
  #
  # @return [void]
  def like!
    increment!(:likes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_engagements_controller.rb
# frozen_string_literal: true

class ArticleEngagementsController < ApplicationController
  def update
    # Ensure that the requested engagement type is valid before proceeding
    raise ActionController::NotImplemented, I18n.t("articles.engagement.not_implemented") unless valid_engagement?

    engagement.public_send(engagement_method)

    redirect_back fallback_location: root_path
  end

  protected

  # The engagement instance for this request
  #
  # @return [ArticleEngagement|ActiveRecord::RecordNotFound]
  def engagement
    @engagement ||= ArticleEngagement.find_by!(article_engagement_params)
  end

  # Is the engagement type requested availble on the engagement instance, ensuring that a user cannot call random
  # methods on the engagement instance
  #
  # @return [Boolean]
  def valid_engagement?
    engagement.respond_to?(engagement_method)
  end

  # Takes a plural engagment type and creates a singular "bang" (!) method name to be called on the engagement.
  # This means we could quickly add new engagement types without new routes or additional controller code, i.e. dislike.
  #
  # @return [Symbol]
  def engagement_method
    "#{engagement_type.singularize}!".to_sym
  end

  # The type of engagement being requested via the params
  #
  # @return [String]
  def engagement_type
    params.require(:engagement)
  end

  # Extract the article ID from the params, which can be passed directly to `find_by`
  #
  # @return [ActionController::Parameters]
  def article_engagement_params
    params.permit(:article_id)
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :retrieve_remote_articles, only: :index

  protected

  def retrieve_remote_articles
    @articles = Olio::ArticlesApiReader.new.perform
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<article class="article col-md-4 mb-4">
  <div class="card">
    <div class="card-header">
      <%= article.title %>
    </div>

    <div class="card-image">
      <img class="card-img-top" src="<%= article.image %>" alt="Card image">
    </div>

    <div class="card-body">
      <small class="text-muted"><%= t("articles.article.added", date: article.date_added) %></small>
      <p class="card-text"><%= article.description %></p>

      <% options = {
        params: { article_id: article.id, engagement: :likes },
        class: "btn btn-warning like-count",
        title: "Click to Like this item",
        method: :put
      } %>
      <%= button_to article_engagements_path, options do %>
        <%== Octicons::Octicon.new("thumbsup").to_svg %> <%= article.engagement.likes %>
      <% end %>
    </div>
  </div>
</article>

app/views/articles/index.html.erb
<div class="container mt-5">
  <h1><%= t("articles.heading") %></h1>
  <p><%= t("articles.intro") %></p>

  <section class="row">
    <div class="col-md-12 mt-4">
      <% if @articles.present? %>
        <div class="row">
          <%= render @articles %>
        </div>
      <% else %>
        <p class="fw-light"><%= t("articles.nothing_found") %></p>
      <% end %>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olio Article Reader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>